spring.application.name=boot-web
server.port=8081
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

#JSP 파일의 위치와 확장자 설정
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#Spring  Boot 3.x는 기본적으로 JSP를 권장하지 않는다. 내부적으로 JSP 랜더링이 다소 불안정할 수 있음.